language: java

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# xvfb creates virtual desktop manager
# DISPLAY=:99.0 specifies that 99th virtual desktop will be used

script: mvn clean test -Pregression
#specifies what exactly will be launched

notifications:
  email:
  - ape999@gmail.com
#sends notifications to email